import { Router, Request, Response } from 'express';
import { getDb } from '../db.js';
import { verifyToken, extractToken } from '../utils/auth.js';

const router = Router();

// ============================================
// 認証ミドルウェア
// ============================================
const authenticate = (req: Request, res: Response, next: Function) => {
  const authHeader = req.headers.authorization;
  const token = extractToken(authHeader);

  console.log('🔐 Authentication check - Header:', authHeader);

  if (!token) {
    console.error('❌ No token found');
    return res.status(401).json({ error: '認証が必要です。トークンが見つかりません。' });
  }

  const decoded = verifyToken(token);
  if (!decoded) {
    console.error('❌ Token verification failed');
    return res.status(401).json({ error: '無効または期限切れのトークンです。' });
  }

  console.log('✅ Token verified - userId:', decoded.userId);
  (req as any).user = decoded;
  next();
};

// ============================================
// GET /api/timeline - timeline 一覧取得（認証必須）
// ============================================
router.get('/', authenticate, (req: Request, res: Response) => {
  try {
    const { stage, autoGenerated } = req.query;
    const user = (req as any).user;
    const db = getDb();

    console.log('📖 Timeline list request - user_id:', user.userId, 'autoGenerated:', autoGenerated);

    let query = 'SELECT * FROM timeline WHERE user_id = ?';
    const params: any[] = [user.userId];

    // autoGenerated=true の場合、AI生成自分史のみを取得
    if (autoGenerated === 'true') {
      query += ' AND is_auto_generated = 1';
      console.log('🤖 Filtering for AI-generated timelines only');
    }

    if (stage) {
      query += ' AND stage = ?';
      params.push(stage);
    }

    query += ' ORDER BY created_at DESC';
    const stmt = db.prepare(query);
    const timelines = stmt.all(...params) as any[];

    console.log('✅ Timeline list:', timelines.length, 'items');
    res.json(timelines);
  } catch (error: any) {
    console.error('❌ Error:', error);
    res.status(500).json({ error: error.message });
  }
});

// ============================================
// POST /api/timeline - timeline 作成（認証必須）
// ============================================
router.post('/', authenticate, (req: Request, res: Response) => {
  try {
    const user = (req as any).user;
    const db = getDb();
    const { age, year, month, turning_point, stage, event_title, event_description, edited_content, answersWithPhotos, isAutoGenerated } = req.body;

    console.log('💾 Timeline creation request:', {
      userId: user.userId,
      eventTitle: event_title,
      hasEditedContent: !!edited_content,
      contentLength: edited_content?.length || 0,
      isAutoGenerated: isAutoGenerated
    });

    // 必須フィールドの検証
    if (!event_title) {
      console.warn('⚠️ Missing event_title');
      return res.status(400).json({
        error: 'event_title is required',
      });
    }

    if (!event_description && !edited_content) {
      console.warn('⚠️ Missing both event_description and edited_content');
      return res.status(400).json({
        error: 'Either event_description or edited_content is required',
      });
    }

    // timeline テーブルに保存
    const stmt = db.prepare(
      `INSERT INTO timeline (user_id, age, year, month, turning_point, stage, event_title, event_description, edited_content, is_auto_generated)
       VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`
    );

    const result = stmt.run(
      user.userId,
      age ? parseInt(age) : null,
      year ? parseInt(year) : null,
      month ? parseInt(month) : null,
      turning_point || null,
      stage || 'interview',
      event_title,
      event_description || null,
      edited_content || null,
      isAutoGenerated ? 1 : 0  // is_auto_generated: AI生成かどうか
    );

    const timelineId = result.lastInsertRowid;
    console.log('✅ Timeline created successfully - id:', timelineId, 'isAutoGenerated:', isAutoGenerated);

    // 写真データを保存（base64 データを直接保存）
    if (answersWithPhotos && Array.isArray(answersWithPhotos)) {
      try {
        const photoStmt = db.prepare(
          `INSERT INTO timeline_photos (timeline_id, file_path, description, display_order, created_at)
           VALUES (?, ?, ?, ?, datetime('now'))`
        );

        let photoCount = 0;
        for (let idx = 0; idx < answersWithPhotos.length; idx++) {
          const answer = answersWithPhotos[idx];
          if (answer.photos && Array.isArray(answer.photos) && answer.photos.length > 0) {
            console.log('📸 Processing answer', idx, '- photo count:', answer.photos.length);
            
            for (let photoIdx = 0; photoIdx < answer.photos.length; photoIdx++) {
              const photo = answer.photos[photoIdx];
              
              console.log('📸 Saving photo:', {
                timelineId,
                answerIdx: idx,
                photoIdx,
                hasFilePath: !!photo.file_path,
                filePathLength: photo.file_path?.length || 0,
                description: photo.description
              });

              photoStmt.run(
                timelineId,
                photo.file_path,  // base64 または URL パス
                photo.description || `Photo from Q${idx + 1}`,
                photoCount
              );
              photoCount++;
              console.log('✅ Photo saved - count:', photoCount, '- description:', photo.description);
            }
          }
        }
        console.log('✅ All photos saved - total:', photoCount, 'for timeline id:', timelineId);
      } catch (photoError: any) {
        console.error('❌ Photo save error:', photoError);
        console.error('❌ Error details:', photoError.message, photoError.stack);
        console.warn('⚠️ Photo save warning:', photoError.message);
        // 写真保存エラーは無視して続行
      }
    }

    // 保存されたデータを取得して返す
    const savedTimeline = db.prepare('SELECT * FROM timeline WHERE id = ?').get(timelineId);

    res.status(201).json({
      success: true,
      message: 'Timeline created successfully',
      data: savedTimeline
    });

  } catch (error: any) {
    console.error('❌ Error in POST /api/timeline:', error);
    res.status(500).json({ 
      error: 'Failed to create timeline',
      details: error.message 
    });
  }
});

// ============================================
// GET /api/timeline/:id - 特定の timeline 取得（認証必須）
// ============================================
router.get('/:id', authenticate, (req: Request, res: Response) => {
  try {
    const { id } = req.params;
    const user = (req as any).user;
    const db = getDb();

    console.log('📖 Timeline detail request - id:', id);

    const stmt = db.prepare('SELECT * FROM timeline WHERE id = ? AND user_id = ?');
    const timeline = stmt.get(id, user.userId);

    if (!timeline) {
      console.warn('⚠️ Timeline not found - id:', id);
      return res.status(404).json({ error: 'Timeline not found' });
    }

    console.log('✅ Timeline retrieved - id:', id);
    res.json(timeline);
  } catch (error: any) {
    console.error('❌ Error:', error);
    res.status(500).json({ error: error.message });
  }
});

// ============================================
// PUT /api/timeline/:id - timeline 更新（認証必須）
// ============================================
router.put('/:id', authenticate, (req: Request, res: Response) => {
  try {
    const { id } = req.params;
    const user = (req as any).user;
    const db = getDb();
    const { age, year, month, turning_point, stage, event_title, event_description, edited_content } = req.body;

    console.log('✏️ Timeline update request - id:', id);

    // 本人確認
    const timeline = db.prepare('SELECT user_id FROM timeline WHERE id = ?').get(id) as any;
    if (!timeline) {
      console.warn('⚠️ Timeline not found - id:', id);
      return res.status(404).json({ error: 'Timeline not found' });
    }

    if (timeline.user_id !== user.userId) {
      console.error('❌ Access denied');
      return res.status(403).json({ error: 'アクセス権限がありません。' });
    }

    const stmt = db.prepare(
      `UPDATE timeline
       SET age = COALESCE(?, age),
           year = COALESCE(?, year),
           month = COALESCE(?, month),
           turning_point = COALESCE(?, turning_point),
           stage = COALESCE(?, stage),
           event_title = COALESCE(?, event_title),
           event_description = COALESCE(?, event_description),
           edited_content = COALESCE(?, edited_content),
           updated_at = datetime('now')
       WHERE id = ?`
    );

    stmt.run(
      age ? parseInt(age) : null,
      year ? parseInt(year) : null,
      month ? parseInt(month) : null,
      turning_point || null,
      stage || null,
      event_title || null,
      event_description || null,
      edited_content || null,
      id
    );

    const updatedTimeline = db.prepare('SELECT * FROM timeline WHERE id = ?').get(id);

    console.log('✅ Timeline updated successfully - id:', id);
    res.json({ 
      success: true,
      message: 'Timeline updated successfully', 
      data: updatedTimeline 
    });
  } catch (error: any) {
    console.error('❌ Error:', error);
    res.status(500).json({ error: error.message });
  }
});

// ============================================
// DELETE /api/timeline/:id - timeline 削除（認証必須）
// ============================================
router.delete('/:id', authenticate, (req: Request, res: Response) => {
  try {
    const { id } = req.params;
    const user = (req as any).user;
    const db = getDb();

    console.log('🗑️ Timeline delete request - id:', id);

    // 本人確認
    const timeline = db.prepare('SELECT user_id FROM timeline WHERE id = ?').get(id) as any;
    if (!timeline) {
      console.warn('⚠️ Timeline not found - id:', id);
      return res.status(404).json({ error: 'Timeline not found' });
    }

    if (timeline.user_id !== user.userId) {
      console.error('❌ Access denied');
      return res.status(403).json({ error: 'アクセス権限がありません。' });
    }

    const stmt = db.prepare('DELETE FROM timeline WHERE id = ?');
    stmt.run(id);

    console.log('✅ Timeline deleted successfully - id:', id);
    res.json({ 
      success: true,
      message: 'Timeline deleted successfully' 
    });
  } catch (error: any) {
    console.error('❌ Error:', error);
    res.status(500).json({ error: error.message });
  }
});

// ============================================
// 📸 写真紐付け関連エンドポイント
// ============================================

// GET /api/timeline/:timelineId/photos - タイムラインの紐付き写真を取得
router.get('/:timelineId/photos', authenticate, (req: Request, res: Response) => {
  try {
    const { timelineId } = req.params;
    const user = (req as any).user;
    const db = getDb();

    console.log('📸 Get timeline photos - timelineId:', timelineId);

    // 本人確認（タイムラインの所有者確認）
    const timeline = db.prepare('SELECT user_id FROM timeline WHERE id = ?').get(timelineId) as any;
    if (!timeline || timeline.user_id !== user.userId) {
      console.error('❌ Access denied');
      return res.status(403).json({ error: 'アクセス権限がありません。' });
    }

    // 紐付き写真を取得
    const stmt = db.prepare(`
      SELECT id, timeline_id, file_path, description, display_order, created_at
      FROM timeline_photos
      WHERE timeline_id = ?
      ORDER BY display_order ASC, created_at ASC
    `);
    const photos = stmt.all(timelineId);

    console.log('✅ Found', photos.length, 'photos for timeline:', timelineId);
    res.json(photos);
  } catch (error: any) {
    console.error('❌ Error:', error);
    res.status(500).json({ error: error.message });
  }
});

// POST /api/timeline/:timelineId/photos - 写真をタイムラインに紐付ける
router.post('/:timelineId/photos', authenticate, (req: Request, res: Response) => {
  try {
    const { timelineId } = req.params;
    const user = (req as any).user;
    const db = getDb();
    const { photoIds, photoData } = req.body;

    console.log('📸 Link photos to timeline - timelineId:', timelineId, 'photoCount:', photoIds?.length || photoData?.length);

    // 本人確認
    const timeline = db.prepare('SELECT user_id FROM timeline WHERE id = ?').get(timelineId) as any;
    if (!timeline || timeline.user_id !== user.userId) {
      console.error('❌ Access denied');
      return res.status(403).json({ error: 'アクセス権限がありません。' });
    }

    let insertedPhotos: any[] = [];

    // パターン1: photo IDs で紐付ける（既存の photos テーブルから取得）
    if (photoIds && Array.isArray(photoIds) && photoIds.length > 0) {
      const photoStmt = db.prepare(`
        SELECT id, file_path, description FROM photos 
        WHERE id = ? AND user_id = ?
      `);

      const insertStmt = db.prepare(`
        INSERT INTO timeline_photos (timeline_id, file_path, description, display_order, created_at)
        VALUES (?, ?, ?, ?, datetime('now'))
      `);

      for (let idx = 0; idx < photoIds.length; idx++) {
        const photoId = photoIds[idx];
        const photo = photoStmt.get(photoId, user.userId) as any;

        if (photo) {
          const result = insertStmt.run(timelineId, photo.file_path, photo.description, idx);
          insertedPhotos.push({
            id: result.lastInsertRowid,
            file_path: photo.file_path,
            description: photo.description,
            display_order: idx
          });
          console.log('✅ Photo linked - photoId:', photoId, 'timelineId:', timelineId);
        } else {
          console.warn('⚠️ Photo not found or not owned by user - photoId:', photoId);
        }
      }
    }

    // パターン2: 直接写真データで紐付ける
    if (photoData && Array.isArray(photoData) && photoData.length > 0) {
      const insertStmt = db.prepare(`
        INSERT INTO timeline_photos (timeline_id, file_path, description, display_order, created_at)
        VALUES (?, ?, ?, ?, datetime('now'))
      `);

      for (let idx = 0; idx < photoData.length; idx++) {
        const photo = photoData[idx];
        const result = insertStmt.run(
          timelineId,
          photo.file_path,
          photo.description || '',
          idx
        );
        insertedPhotos.push({
          id: result.lastInsertRowid,
          file_path: photo.file_path,
          description: photo.description || '',
          display_order: idx
        });
        console.log('✅ Photo data linked - timelineId:', timelineId);
      }
    }

    res.status(201).json({
      success: true,
      message: `${insertedPhotos.length} photos linked successfully`,
      data: insertedPhotos
    });

  } catch (error: any) {
    console.error('❌ Error:', error);
    res.status(500).json({ error: error.message });
  }
});

// DELETE /api/timeline/:timelineId/photos/:photoId - 紐付きを削除
router.delete('/:timelineId/photos/:photoId', authenticate, (req: Request, res: Response) => {
  try {
    const { timelineId, photoId } = req.params;
    const user = (req as any).user;
    const db = getDb();

    console.log('🗑️ Unlink photo - timelineId:', timelineId, 'photoId:', photoId);

    // 本人確認
    const timeline = db.prepare('SELECT user_id FROM timeline WHERE id = ?').get(timelineId) as any;
    if (!timeline || timeline.user_id !== user.userId) {
      console.error('❌ Access denied');
      return res.status(403).json({ error: 'アクセス権限がありません。' });
    }

    const stmt = db.prepare('DELETE FROM timeline_photos WHERE id = ? AND timeline_id = ?');
    stmt.run(photoId, timelineId);

    console.log('✅ Photo unlinked successfully');
    res.json({
      success: true,
      message: 'Photo unlinked successfully'
    });
  } catch (error: any) {
    console.error('❌ Error:', error);
    res.status(500).json({ error: error.message });
  }
});

// ============================================
// POST /api/timeline/:timelineId/metadata - timeline_metadata 作成
// ============================================
router.post('/:timelineId/metadata', authenticate, (req: Request, res: Response) => {
  try {
    const user = (req as any).user;
    const db = getDb();
    const { timelineId } = req.params;
    const { user_id, important_events, turning_points, custom_metadata } = req.body;

    console.log('📊 timeline_metadata creation request:', {
      userId: user.userId,
      timelineId,
      hasImportantEvents: !!important_events,
      hasTurningPoints: !!turning_points
    });

    // user_id の検証
    if (user_id !== user.userId) {
      console.error('❌ User ID mismatch');
      return res.status(403).json({ error: 'アクセス権限がありません' });
    }

    // timeline が存在するか確認
    const timeline = db.prepare('SELECT * FROM timeline WHERE id = ? AND user_id = ?').get(timelineId, user.userId) as any;
    if (!timeline) {
      console.error('❌ Timeline not found');
      return res.status(404).json({ error: 'Timeline が見つかりません' });
    }

    // ✅ timeline_metadata に挿入（既存の場合は無視、新規の場合のみ作成）
    try {
      const stmt = db.prepare(`
        INSERT INTO timeline_metadata (
          user_id, 
          timeline_id, 
          important_events, 
          turning_points, 
          custom_metadata, 
          created_at
        ) VALUES (?, ?, ?, ?, ?, datetime('now'))
      `);

      stmt.run(
        user.userId,
        timelineId,
        important_events || '[]',  // JSON文字列として保存
        turning_points || '[]',    // JSON文字列として保存
        custom_metadata ? JSON.stringify(custom_metadata) : '{}'
      );

      console.log('✅ timeline_metadata created successfully - timelineId:', timelineId);

      res.json({
        success: true,
        message: 'timeline_metadata created successfully',
        timelineId
      });

    } catch (dbError: any) {
      // UNIQUE 制約による重複エラーの場合は無視
      if (dbError.message.includes('UNIQUE')) {
        console.log('⚠️ timeline_metadata already exists for this timeline');
        return res.json({
          success: true,
          message: 'timeline_metadata already exists',
          timelineId
        });
      }
      throw dbError;
    }

  } catch (error: any) {
    console.error('❌ Error in POST /api/timeline/:timelineId/metadata:', error);
    res.status(500).json({ 
      error: 'timeline_metadata 作成に失敗しました',
      details: error.message 
    });
  }
});

export default router;